<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "detaktawebsite"
 *
 * Auto generated by Extension Builder 2017-11-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$_EXTKEY = 'detaktawebsite';
$EXTKEY = 'detaktawebsite';

$EM_CONF[$_EXTKEY] = [
    'title' => 'Detakta Website',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Eike Lars Henke',
    'author_email' => 'eike.henke@itechnology.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-10.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
